// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: src/pkg/transformer/transformer.proto

package transformer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransformVideoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path of the video on S3.
	Videopath       string   `protobuf:"bytes,1,opt,name=videopath,proto3" json:"videopath,omitempty"`
	TransformerList []string `protobuf:"bytes,2,rep,name=transformer_list,json=transformerList,proto3" json:"transformer_list,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransformVideoRequest) Reset() {
	*x = TransformVideoRequest{}
	mi := &file_src_pkg_transformer_transformer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformVideoRequest) ProtoMessage() {}

func (x *TransformVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_pkg_transformer_transformer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformVideoRequest.ProtoReflect.Descriptor instead.
func (*TransformVideoRequest) Descriptor() ([]byte, []int) {
	return file_src_pkg_transformer_transformer_proto_rawDescGZIP(), []int{0}
}

func (x *TransformVideoRequest) GetVideopath() string {
	if x != nil {
		return x.Videopath
	}
	return ""
}

func (x *TransformVideoRequest) GetTransformerList() []string {
	if x != nil {
		return x.TransformerList
	}
	return nil
}

type TransformVideoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The video part, as byte array.
	Chunk         []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformVideoResponse) Reset() {
	*x = TransformVideoResponse{}
	mi := &file_src_pkg_transformer_transformer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformVideoResponse) ProtoMessage() {}

func (x *TransformVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_pkg_transformer_transformer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformVideoResponse.ProtoReflect.Descriptor instead.
func (*TransformVideoResponse) Descriptor() ([]byte, []int) {
	return file_src_pkg_transformer_transformer_proto_rawDescGZIP(), []int{1}
}

func (x *TransformVideoResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_src_pkg_transformer_transformer_proto protoreflect.FileDescriptor

const file_src_pkg_transformer_transformer_proto_rawDesc = "" +
	"\n" +
	"%src/pkg/transformer/transformer.proto\x12\x12pkg.transformer.v1\"`\n" +
	"\x15TransformVideoRequest\x12\x1c\n" +
	"\tvideopath\x18\x01 \x01(\tR\tvideopath\x12)\n" +
	"\x10transformer_list\x18\x02 \x03(\tR\x0ftransformerList\".\n" +
	"\x16TransformVideoResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2\x81\x01\n" +
	"\x12TransformerService\x12k\n" +
	"\x0eTransformVideo\x12).pkg.transformer.v1.TransformVideoRequest\x1a*.pkg.transformer.v1.TransformVideoResponse\"\x000\x01B3Z1github.com/rishirishhh/vought/src/pkg/transformerb\x06proto3"

var (
	file_src_pkg_transformer_transformer_proto_rawDescOnce sync.Once
	file_src_pkg_transformer_transformer_proto_rawDescData []byte
)

func file_src_pkg_transformer_transformer_proto_rawDescGZIP() []byte {
	file_src_pkg_transformer_transformer_proto_rawDescOnce.Do(func() {
		file_src_pkg_transformer_transformer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_pkg_transformer_transformer_proto_rawDesc), len(file_src_pkg_transformer_transformer_proto_rawDesc)))
	})
	return file_src_pkg_transformer_transformer_proto_rawDescData
}

var file_src_pkg_transformer_transformer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_pkg_transformer_transformer_proto_goTypes = []any{
	(*TransformVideoRequest)(nil),  // 0: pkg.transformer.v1.TransformVideoRequest
	(*TransformVideoResponse)(nil), // 1: pkg.transformer.v1.TransformVideoResponse
}
var file_src_pkg_transformer_transformer_proto_depIdxs = []int32{
	0, // 0: pkg.transformer.v1.TransformerService.TransformVideo:input_type -> pkg.transformer.v1.TransformVideoRequest
	1, // 1: pkg.transformer.v1.TransformerService.TransformVideo:output_type -> pkg.transformer.v1.TransformVideoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_pkg_transformer_transformer_proto_init() }
func file_src_pkg_transformer_transformer_proto_init() {
	if File_src_pkg_transformer_transformer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_pkg_transformer_transformer_proto_rawDesc), len(file_src_pkg_transformer_transformer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_pkg_transformer_transformer_proto_goTypes,
		DependencyIndexes: file_src_pkg_transformer_transformer_proto_depIdxs,
		MessageInfos:      file_src_pkg_transformer_transformer_proto_msgTypes,
	}.Build()
	File_src_pkg_transformer_transformer_proto = out.File
	file_src_pkg_transformer_transformer_proto_goTypes = nil
	file_src_pkg_transformer_transformer_proto_depIdxs = nil
}
