// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: src/pkg/transformer/transformer.proto

package transformer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransformerService_TransformVideo_FullMethodName = "/pkg.transformer.v1.TransformerService/TransformVideo"
)

// TransformerServiceClient is the client API for TransformerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransformerServiceClient interface {
	// Obtains the feature at a given position.
	TransformVideo(ctx context.Context, in *TransformVideoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransformVideoResponse], error)
}

type transformerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransformerServiceClient(cc grpc.ClientConnInterface) TransformerServiceClient {
	return &transformerServiceClient{cc}
}

func (c *transformerServiceClient) TransformVideo(ctx context.Context, in *TransformVideoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransformVideoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TransformerService_ServiceDesc.Streams[0], TransformerService_TransformVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransformVideoRequest, TransformVideoResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransformerService_TransformVideoClient = grpc.ServerStreamingClient[TransformVideoResponse]

// TransformerServiceServer is the server API for TransformerService service.
// All implementations must embed UnimplementedTransformerServiceServer
// for forward compatibility.
type TransformerServiceServer interface {
	// Obtains the feature at a given position.
	TransformVideo(*TransformVideoRequest, grpc.ServerStreamingServer[TransformVideoResponse]) error
	mustEmbedUnimplementedTransformerServiceServer()
}

// UnimplementedTransformerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransformerServiceServer struct{}

func (UnimplementedTransformerServiceServer) TransformVideo(*TransformVideoRequest, grpc.ServerStreamingServer[TransformVideoResponse]) error {
	return status.Errorf(codes.Unimplemented, "method TransformVideo not implemented")
}
func (UnimplementedTransformerServiceServer) mustEmbedUnimplementedTransformerServiceServer() {}
func (UnimplementedTransformerServiceServer) testEmbeddedByValue()                            {}

// UnsafeTransformerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransformerServiceServer will
// result in compilation errors.
type UnsafeTransformerServiceServer interface {
	mustEmbedUnimplementedTransformerServiceServer()
}

func RegisterTransformerServiceServer(s grpc.ServiceRegistrar, srv TransformerServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransformerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransformerService_ServiceDesc, srv)
}

func _TransformerService_TransformVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransformVideoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransformerServiceServer).TransformVideo(m, &grpc.GenericServerStream[TransformVideoRequest, TransformVideoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransformerService_TransformVideoServer = grpc.ServerStreamingServer[TransformVideoResponse]

// TransformerService_ServiceDesc is the grpc.ServiceDesc for TransformerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransformerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pkg.transformer.v1.TransformerService",
	HandlerType: (*TransformerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransformVideo",
			Handler:       _TransformerService_TransformVideo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/pkg/transformer/transformer.proto",
}
