// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: src/pkg/contracts/v1/video.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Video_VideoStatus int32

const (
	Video_VIDEO_STATUS_UNSPECIFIED Video_VideoStatus = 0
	Video_VIDEO_STATUS_UPLOADING   Video_VideoStatus = 1
	Video_VIDEO_STATUS_UPLOADED    Video_VideoStatus = 2
	Video_VIDEO_STATUS_ENCODING    Video_VideoStatus = 3
	Video_VIDEO_STATUS_COMPLETE    Video_VideoStatus = 4
	Video_VIDEO_STATUS_UNKNOWN     Video_VideoStatus = 5
	Video_VIDEO_STATUS_FAIL_UPLOAD Video_VideoStatus = 6
	Video_VIDEO_STATUS_FAIL_ENCODE Video_VideoStatus = 7
)

// Enum value maps for Video_VideoStatus.
var (
	Video_VideoStatus_name = map[int32]string{
		0: "VIDEO_STATUS_UNSPECIFIED",
		1: "VIDEO_STATUS_UPLOADING",
		2: "VIDEO_STATUS_UPLOADED",
		3: "VIDEO_STATUS_ENCODING",
		4: "VIDEO_STATUS_COMPLETE",
		5: "VIDEO_STATUS_UNKNOWN",
		6: "VIDEO_STATUS_FAIL_UPLOAD",
		7: "VIDEO_STATUS_FAIL_ENCODE",
	}
	Video_VideoStatus_value = map[string]int32{
		"VIDEO_STATUS_UNSPECIFIED": 0,
		"VIDEO_STATUS_UPLOADING":   1,
		"VIDEO_STATUS_UPLOADED":    2,
		"VIDEO_STATUS_ENCODING":    3,
		"VIDEO_STATUS_COMPLETE":    4,
		"VIDEO_STATUS_UNKNOWN":     5,
		"VIDEO_STATUS_FAIL_UPLOAD": 6,
		"VIDEO_STATUS_FAIL_ENCODE": 7,
	}
)

func (x Video_VideoStatus) Enum() *Video_VideoStatus {
	p := new(Video_VideoStatus)
	*p = x
	return p
}

func (x Video_VideoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Video_VideoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_src_pkg_contracts_v1_video_proto_enumTypes[0].Descriptor()
}

func (Video_VideoStatus) Type() protoreflect.EnumType {
	return &file_src_pkg_contracts_v1_video_proto_enumTypes[0]
}

func (x Video_VideoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Video_VideoStatus.Descriptor instead.
func (Video_VideoStatus) EnumDescriptor() ([]byte, []int) {
	return file_src_pkg_contracts_v1_video_proto_rawDescGZIP(), []int{0, 0}
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Video_VideoStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=pkg.contracts.v1.Video_VideoStatus" json:"status,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	CoverPath     string                 `protobuf:"bytes,4,opt,name=cover_path,json=coverPath,proto3" json:"cover_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_src_pkg_contracts_v1_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_src_pkg_contracts_v1_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_src_pkg_contracts_v1_video_proto_rawDescGZIP(), []int{0}
}

func (x *Video) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Video) GetStatus() Video_VideoStatus {
	if x != nil {
		return x.Status
	}
	return Video_VIDEO_STATUS_UNSPECIFIED
}

func (x *Video) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Video) GetCoverPath() string {
	if x != nil {
		return x.CoverPath
	}
	return ""
}

var File_src_pkg_contracts_v1_video_proto protoreflect.FileDescriptor

const file_src_pkg_contracts_v1_video_proto_rawDesc = "" +
	"\n" +
	" src/pkg/contracts/v1/video.proto\x12\x10pkg.contracts.v1\"\xfc\x02\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.pkg.contracts.v1.Video.VideoStatusR\x06status\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"cover_path\x18\x04 \x01(\tR\tcoverPath\"\xee\x01\n" +
	"\vVideoStatus\x12\x1c\n" +
	"\x18VIDEO_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16VIDEO_STATUS_UPLOADING\x10\x01\x12\x19\n" +
	"\x15VIDEO_STATUS_UPLOADED\x10\x02\x12\x19\n" +
	"\x15VIDEO_STATUS_ENCODING\x10\x03\x12\x19\n" +
	"\x15VIDEO_STATUS_COMPLETE\x10\x04\x12\x18\n" +
	"\x14VIDEO_STATUS_UNKNOWN\x10\x05\x12\x1c\n" +
	"\x18VIDEO_STATUS_FAIL_UPLOAD\x10\x06\x12\x1c\n" +
	"\x18VIDEO_STATUS_FAIL_ENCODE\x10\aB7Z5github.com/rishirishhh/vought/src/pkg/contracts/v1;v1b\x06proto3"

var (
	file_src_pkg_contracts_v1_video_proto_rawDescOnce sync.Once
	file_src_pkg_contracts_v1_video_proto_rawDescData []byte
)

func file_src_pkg_contracts_v1_video_proto_rawDescGZIP() []byte {
	file_src_pkg_contracts_v1_video_proto_rawDescOnce.Do(func() {
		file_src_pkg_contracts_v1_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_pkg_contracts_v1_video_proto_rawDesc), len(file_src_pkg_contracts_v1_video_proto_rawDesc)))
	})
	return file_src_pkg_contracts_v1_video_proto_rawDescData
}

var file_src_pkg_contracts_v1_video_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_pkg_contracts_v1_video_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_pkg_contracts_v1_video_proto_goTypes = []any{
	(Video_VideoStatus)(0), // 0: pkg.contracts.v1.Video.VideoStatus
	(*Video)(nil),          // 1: pkg.contracts.v1.Video
}
var file_src_pkg_contracts_v1_video_proto_depIdxs = []int32{
	0, // 0: pkg.contracts.v1.Video.status:type_name -> pkg.contracts.v1.Video.VideoStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_pkg_contracts_v1_video_proto_init() }
func file_src_pkg_contracts_v1_video_proto_init() {
	if File_src_pkg_contracts_v1_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_pkg_contracts_v1_video_proto_rawDesc), len(file_src_pkg_contracts_v1_video_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_pkg_contracts_v1_video_proto_goTypes,
		DependencyIndexes: file_src_pkg_contracts_v1_video_proto_depIdxs,
		EnumInfos:         file_src_pkg_contracts_v1_video_proto_enumTypes,
		MessageInfos:      file_src_pkg_contracts_v1_video_proto_msgTypes,
	}.Build()
	File_src_pkg_contracts_v1_video_proto = out.File
	file_src_pkg_contracts_v1_video_proto_goTypes = nil
	file_src_pkg_contracts_v1_video_proto_depIdxs = nil
}
